name: Build the plugin using Gradle
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.x.x
      - name: Build the plugin using Gradle
        run: |
          ./gradlew buildPlugin
          ./gradlew verifyPlugin
      - uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.3
        with:
          ide-versions: |
            ideaIC:2019.3.3
            ideaIU:2019.3.3
            ideaIC:2020.2
            ideaIU:2020.2
            ideaIC:LATEST-EAP-SNAPSHOT
            ideaIU:LATEST-EAP-SNAPSHOT
